oauth2:
    google:
        client-id:
        client-secret:
        redirect-uri:
        token-uri:
        resource-uri:

spring:
    data:
        redis:
            host: localhost
            port: 6379